# Generated by Django 4.2.3 on 2023-08-26 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweep',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_tweeps', to=settings.AUTH_USER_MODEL),
        ),
    ]
